use serde::{Deserialize, Serialize};
use tauri::Manager;
use std::{fs, path::PathBuf, sync::{Arc, Mutex}, thread, time::{Duration, Instant}};

#[derive(Clone, Serialize, Deserialize, Default)]
struct AppActivity { app: String, title: String, seconds: u64, activations: u64 }
#[derive(Clone, Serialize, Deserialize, Default)]
struct TimelineEvent { at: String, app: String, title: String, kind: String }
#[derive(Clone, Serialize, Deserialize, Default)]
struct MinuteSnapshot { at: String, active_app_count: u64, focus_seconds: u64, keyboard_actions: u64, mouse_actions: u64, mouse_distance_px: f64, network_rx_bytes: u64, network_tx_bytes: u64 }
#[derive(Clone, Serialize, Deserialize)]
struct TrackingState {
    enabled: bool, active_window: String, keyboard_actions: u64, mouse_actions: u64, app_activation_count: u64, focus_seconds: u64,
    hourly_focus: [u64; 24], apps: Vec<AppActivity>, timeline: Vec<TimelineEvent>, minute_snapshots: Vec<MinuteSnapshot>,
    active_app_count: u64, mouse_distance_px: f64, mouse_clicks: u64, avg_click_interval_ms: u64, network_rx_bytes: u64, network_tx_bytes: u64,
    notification_count: u64,
}
impl Default for TrackingState { fn default() -> Self { Self { enabled:true, active_window:String::new(), keyboard_actions:0, mouse_actions:0, app_activation_count:0, focus_seconds:0, hourly_focus:[0;24], apps:Vec::new(), timeline:Vec::new(), minute_snapshots:Vec::new(), active_app_count:0, mouse_distance_px:0.0, mouse_clicks:0, avg_click_interval_ms:0, network_rx_bytes:0, network_tx_bytes:0, notification_count:0 } } }
type SharedState = Arc<Mutex<TrackingState>>; type SharedPath = Arc<Mutex<PathBuf>>;
fn save(s:&TrackingState,p:&PathBuf)->Result<(),String>{if let Some(x)=p.parent(){fs::create_dir_all(x).map_err(|e|e.to_string())?}let b=serde_json::to_vec_pretty(s).map_err(|e|e.to_string())?;let t=p.with_extension("json.tmp");fs::write(&t,b).map_err(|e|e.to_string())?;fs::rename(t,p).map_err(|e|e.to_string())}
fn load(p:&PathBuf)->TrackingState{fs::read(p).ok().and_then(|b|serde_json::from_slice(&b).ok()).unwrap_or_default()}
fn pv(p:&SharedPath)->Result<PathBuf,String>{p.lock().map(|x|x.clone()).map_err(|_|"storage path unavailable".into())}
#[tauri::command] fn set_tracking(enabled:bool,state:tauri::State<'_,SharedState>,path:tauri::State<'_,SharedPath>)->Result<TrackingState,String>{let mut s=state.lock().map_err(|_|"state unavailable")?;s.enabled=enabled;save(&s,&pv(&path)?)?;Ok(s.clone())}
#[tauri::command] fn get_tracking_state(state:tauri::State<'_,SharedState>)->Result<TrackingState,String>{state.lock().map(|x|x.clone()).map_err(|_|"state unavailable".into())}
#[tauri::command] fn clear_all_data(state:tauri::State<'_,SharedState>,path:tauri::State<'_,SharedPath>)->Result<(),String>{let mut s=state.lock().map_err(|_|"state unavailable")?;let e=s.enabled;*s=TrackingState{enabled:e,..Default::default()};let p=pv(&path)?;if p.exists(){fs::remove_file(p).map_err(|x|x.to_string())?}Ok(())}

#[cfg(windows)] fn active_window()->String{use windows::Win32::Foundation::HWND;use windows::Win32::UI::WindowsAndMessaging::{GetForegroundWindow,GetWindowTextW};let h=unsafe{GetForegroundWindow()};if h==HWND::default(){return String::new()}let mut b=[0u16;512];let n=unsafe{GetWindowTextW(h,&mut b)};String::from_utf16_lossy(&b[..n as usize])}
#[cfg(windows)] fn network_totals()->(u64,u64){use windows::Win32::NetworkManagement::IpHelper::{GetIfTable2,FreeMibTable,MIB_IF_TABLE2};let mut p:*mut MIB_IF_TABLE2=std::ptr::null_mut();let r=unsafe{GetIfTable2(&mut p)};if r.0!=0||p.is_null(){return(0,0)}let t=unsafe{&*p};let mut rx=0;let mut tx=0;for i in 0..t.NumEntries as usize{let row=unsafe{*t.Table.add(i)};rx+=row.InOctets;tx+=row.OutOctets}unsafe{FreeMibTable(p as _)};(rx,tx)}
#[cfg(not(windows))] fn network_totals()->(u64,u64){(0,0)}
#[cfg(windows)] fn tracker(state:SharedState,path:SharedPath){use chrono::{Local,Timelike};use windows::Win32::Foundation::POINT;use windows::Win32::UI::Input::KeyboardAndMouse::{GetAsyncKeyState,VK_LBUTTON,VK_RBUTTON};use windows::Win32::UI::WindowsAndMessaging::GetCursorPos;thread::spawn(move||{let mut prev=String::new();let mut pos=POINT{x:0,y:0};let mut last_click:Option<Instant>=None;let mut last_min=Local::now().minute();loop{thread::sleep(Duration::from_secs(1));let Ok(mut s)=state.lock()else{continue};if !s.enabled{continue}let now=Local::now();let w=active_window();if w!=prev&&!w.is_empty(){s.app_activation_count+=1;s.timeline.push(TimelineEvent{at:now.to_rfc3339(),app:w.clone(),title:w.clone(),kind:"app_switch".into()});prev=w.clone()}s.active_window=w.clone();s.focus_seconds+=1;s.hourly_focus[now.hour()as usize]+=1;s.active_app_count=s.apps.len()as u64;if let Some(a)=s.apps.iter_mut().find(|a|a.app==w){a.seconds+=1;a.title=w.clone()}else if !w.is_empty(){s.apps.push(AppActivity{app:w.clone(),title:w.clone(),seconds:1,activations:1})}let mut q=POINT{x:0,y:0};if unsafe{GetCursorPos(&mut q)}.is_ok(){let dx=(q.x-pos.x)as f64;let dy=(q.y-pos.y)as f64;s.mouse_distance_px+=(dx*dx+dy*dy).sqrt();if q.x!=pos.x||q.y!=pos.y{s.mouse_actions+=1}pos=q}if unsafe{GetAsyncKeyState(VK_LBUTTON.0 as i32)}<0||unsafe{GetAsyncKeyState(VK_RBUTTON.0 as i32)}<0{s.mouse_clicks+=1;if let Some(t)=last_click{s.avg_click_interval_ms=if s.avg_click_interval_ms==0{t.elapsed().as_millis()as u64}else{(s.avg_click_interval_ms+t.elapsed().as_millis()as u64)/2}}last_click=Some(Instant::now())}for k in 0..=0xfe{if unsafe{GetAsyncKeyState(k)}<0{s.keyboard_actions+=1;break}}if now.minute()!=last_min{let(rx,tx)=network_totals();s.network_rx_bytes=rx;s.network_tx_bytes=tx;s.minute_snapshots.push(MinuteSnapshot{at:now.to_rfc3339(),active_app_count:s.active_app_count,focus_seconds:s.focus_seconds,keyboard_actions:s.keyboard_actions,mouse_actions:s.mouse_actions,mouse_distance_px:s.mouse_distance_px,network_rx_bytes:rx,network_tx_bytes:tx});if s.minute_snapshots.len()>1440{s.minute_snapshots.remove(0); }last_min=now.minute()}let _=pv(&path).and_then(|p|save(&s,&p));}})}
#[cfg(not(windows))]fn tracker(_:SharedState,_:SharedPath){}
#[cfg_attr(mobile,tauri::mobile_entry_point)]pub fn run(){let s=Arc::new(Mutex::new(TrackingState::default()));let p=Arc::new(Mutex::new(PathBuf::new()));let ss=s.clone();let pp=p.clone();tauri::Builder::default().setup(move|app|{let f=app.path().app_data_dir().map_err(|e|e.to_string())?.join("activity.json");if let Ok(mut x)=ss.lock(){*x=load(&f)}if let Ok(mut x)=pp.lock(){*x=f}tracker(ss.clone(),pp.clone());Ok(())}).manage(s).manage(p).invoke_handler(tauri::generate_handler![set_tracking,get_tracking_state,clear_all_data]).run(tauri::generate_context!()).expect("error while running FlowLens")}
