import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { invoke } from '@tauri-apps/api/core';
import './styles.css';

type AppActivity = { app: string; title: string; seconds: number; activations: number };
type MinuteSnapshot = { at: string; active_app_count: number; focus_seconds: number; keyboard_actions: number; mouse_actions: number; mouse_distance_px: number; network_rx_bytes: number; network_tx_bytes: number };
type TimelineEvent = { at: string; app: string; title: string; kind: string };
type DashboardData = { enabled: boolean; active_window: string; keyboard_actions: number; mouse_actions: number; app_activation_count: number; focus_seconds: number; hourly_focus: number[]; apps: AppActivity[]; timeline: TimelineEvent[]; minute_snapshots: MinuteSnapshot[]; active_app_count: number; mouse_distance_px: number; mouse_clicks: number; avg_click_interval_ms: number; network_rx_bytes: number; network_tx_bytes: number; notification_count: number };
const empty: DashboardData = { enabled: true, active_window: '', keyboard_actions: 0, mouse_actions: 0, app_activation_count: 0, focus_seconds: 0, hourly_focus: Array(24).fill(0), apps: [], timeline: [], minute_snapshots: [], active_app_count: 0, mouse_distance_px: 0, mouse_clicks: 0, avg_click_interval_ms: 0, network_rx_bytes: 0, network_tx_bytes: 0, notification_count: 0 };
const palette = ['#8b5cf6','#22c55e','#f59e0b','#38bdf8','#ec4899','#14b8a6'];
function Icon({ name, size = 18 }: { name: string; size?: number }) { const paths: Record<string,string> = { grid:'M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z', trend:'M4 17l5-5 3 3 7-8M15 7h4v4', clock:'M12 7v5l3 2M21 12a9 9 0 11-18 0 9 9 0 0118 0', mouse:'M12 2a7 7 0 017 7v6a7 7 0 01-14 0V9a7 7 0 017-7zm0 0v6', settings:'M12 15.5a3.5 3.5 0 100-7 3.5 3.5 0 000 7zM19.4 15a1.8 1.8 0 000 2.5l.1.1-1.8 1.8-.1-.1a1.8 1.8 0 00-2.5 0 1.8 1.8 0 00-.5 1.2v.2h-2.6v-.2a1.8 1.8 0 00-3.1-1.2 1.8 1.8 0 00-2.5 0l-.1.1-1.8-1.8.1-.1a1.8 1.8 0 000-2.5 1.8 1.8 0 00-1.2-.5h-.2v-2.6h.2a1.8 1.8 0 001.2-3.1 1.8 1.8 0 000-2.5l-.1-.1 1.8-1.8.1.1a1.8 1.8 0 002.5 0 1.8 1.8 0 00.5-1.2v-.2h2.6v.2a1.8 1.8 0 003.1 1.2 1.8 1.8 0 002.5 0l.1-.1 1.8 1.8-.1.1a1.8 1.8 0 000 2.5 1.8 1.8 0 001.2.5h.2v2.6h-.2a1.8 1.8 0 00-1.2.5z' }; return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name] || paths.grid}/></svg>; }
const mins = (s:number) => s < 60 ? `${s}초` : `${Math.floor(s/60)}분 ${s%60 ? `${s%60}초` : ''}`;
const bytes = (n:number) => n < 1024 ? `${n} B` : n < 1024**2 ? `${(n/1024).toFixed(1)} KB` : n < 1024**3 ? `${(n/1024**2).toFixed(1)} MB` : `${(n/1024**3).toFixed(2)} GB`;
const time = (s:string) => new Date(s).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});
function App() {
 const [data,setData] = useState(empty); const [nav,setNav] = useState('overview'); const [settings,setSettings] = useState(false); const [confirm,setConfirm] = useState(false); const [now,setNow] = useState(new Date());
 const refresh = async () => { try { const d = await invoke<DashboardData>('get_tracking_state'); setData(d); } catch { /* browser preview deliberately remains empty */ } };
 useEffect(() => { refresh(); const id = setInterval(() => { refresh(); setNow(new Date()); }, 2000); return () => clearInterval(id); }, []);
 const toggle = async () => { try { const d = await invoke<DashboardData>('set_tracking',{enabled:!data.enabled}); setData(d); } catch {} };
 const clear = async () => { try { await invoke('clear_all_data'); setData({...empty,enabled:data.enabled}); setConfirm(false); } catch {} };
 const apps = useMemo(() => [...data.apps].sort((a,b)=>b.seconds-a.seconds).slice(0,6),[data.apps]); const maxHour = Math.max(1,...data.hourly_focus); const total = Math.floor(data.focus_seconds/60);
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">F</div><span>FlowLens</span><span className="beta">LOCAL</span></div><div className="workspace"><div className="workspace-avatar">JB</div><div><strong>JB's workspace</strong><small>이 기기에서만 분석</small></div></div><nav>{[['overview','grid','개요'],['focus','trend','집중 분석'],['timeline','clock','타임라인'],['devices','mouse','활동 추적']].map(([id,icon,label])=><button key={id} className={nav===id?'nav-item active':'nav-item'} onClick={()=>setNav(id)}><Icon name={icon}/><span>{label}</span></button>)}</nav><div className="side-bottom"><button className="nav-item" onClick={()=>setSettings(true)}><Icon name="settings"/><span>설정</span></button><div className="privacy-note"><span className="lock">⌑</span><div><b>외부 전송 없음</b><small>활동 데이터는 이 기기에만 저장됩니다.</small></div></div><div className="version">FlowLens v0.2.2</div></div></aside>
 <main className="main"><header className="topbar"><div><p className="eyebrow">LOCAL ACTIVITY DASHBOARD</p><h1>좋은 흐름을 만들고 있어요, JB <span>✦</span></h1></div><div className="header-actions"><div className="live"><i className={data.enabled?'pulse':''}></i>{data.enabled?'실제 추적 중':'추적 일시정지'} <span>·</span>{now.toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</div><button className="avatar">JB</button></div></header><div className="content"><div className="toolbar"><div className="tabs"><button className="selected">오늘</button><button disabled>이번 주</button><button disabled>이번 달</button></div><button className="track-btn" onClick={toggle}><i className={data.enabled?'pulse':''}></i>{data.enabled?'추적 일시정지':'추적 시작'}</button></div>
 <section className="metrics"><div className="metric-card highlight"><div className="metric-icon purple"><Icon name="clock"/></div><div><span>오늘 실제 활동 시간</span><strong>{Math.floor(total/60)}h {total%60}m</strong><small><b>{data.apps.length}</b>개 앱에서 수집됨</small></div></div><div className="metric-card"><div className="metric-icon orange"><Icon name="trend"/></div><div><span>앱 활성화</span><strong>{data.app_activation_count} <small>회</small></strong><small>창 전환 횟수</small></div></div><div className="metric-card"><div className="metric-icon blue"><Icon name="mouse"/></div><div><span>키보드 & 마우스</span><strong>{(data.keyboard_actions+data.mouse_actions).toLocaleString()} <small>액션</small></strong><small>내용은 저장하지 않음</small></div></div></section><section className="metrics"><div className="metric-card"><div className="metric-icon blue"><Icon name="mouse"/></div><div><span>마우스 이동 거리</span><strong>{Math.round(data.mouse_distance_px).toLocaleString()} <small>px</small></strong><small>{data.mouse_clicks}회 클릭 · 평균 {data.avg_click_interval_ms}ms</small></div></div><div className="metric-card"><div className="metric-icon orange"><Icon name="trend"/></div><div><span>네트워크 사용량</span><strong>{bytes(data.network_rx_bytes+data.network_tx_bytes)}</strong><small>수신 {bytes(data.network_rx_bytes)} · 송신 {bytes(data.network_tx_bytes)}</small></div></div><div className="metric-card"><div className="metric-icon purple"><Icon name="clock"/></div><div><span>분당 활성 앱 수</span><strong>{data.active_app_count} <small>개</small></strong><small>알림 추적 준비 중: {data.notification_count}회</small></div></div></section>
 <section className="grid-top"><div className="panel focus-panel"><div className="panel-head"><div><h2>실제 집중 흐름</h2><p>활성 창이 감지된 시간(초)</p></div><div className="legend"><i></i>로컬 수집 데이터</div></div><div className="hour-bars">{data.hourly_focus.map((v,i)=><div className="hour-bar" key={i}><i style={{height:`${Math.max(3,(v/maxHour)*100)}%`}}/><small>{i%3===0?`${String(i).padStart(2,'0')}:00`:''}</small></div>)}</div><div className="insight"><span className="insight-icon">✦</span><div><b>{data.focus_seconds ? 'Windows 활성 창을 실제로 기록하고 있습니다' : '아직 수집된 활동 데이터가 없습니다'}</b><p>{data.focus_seconds ? `현재 활성 창: ${data.active_window || '확인 중'} · 1초 간격으로 로컬 집계 중입니다.` : '앱을 켜 둔 상태로 작업하면 앱별 시간과 입력량이 여기에 표시됩니다.'}</p></div></div></div>
 <div className="panel apps-panel"><div className="panel-head"><div><h2>가장 많이 사용한 앱</h2><p>실제 활성 창 제목 기준</p></div></div>{apps.length ? <div className="app-list">{apps.map((a,i)=><div className="app-row" key={a.app}><div className="app-symbol" style={{background:palette[i%palette.length]}}>{a.app.slice(0,1).toUpperCase()}</div><div className="app-info"><div><b title={a.app}>{a.app}</b><span>{mins(a.seconds)}</span></div><small>{a.title}</small><div className="progress"><i style={{width:`${Math.max(4,(a.seconds/apps[0].seconds)*100)}%`,background:palette[i%palette.length]}}/></div></div><span className="rank">0{i+1}</span></div>)}</div> : <div className="empty-state">활성 앱 데이터 수집 대기 중</div>}</div></section>
 <section className="grid-bottom"><div className="panel websites-panel"><div className="panel-head"><div><h2>웹사이트 활동</h2><p>개인정보 보호를 위해 URL은 수집하지 않습니다</p></div></div><div className="empty-state">브라우저 주소와 페이지 내용은 읽지 않습니다.<br/>현재는 브라우저 창의 앱/창 제목만 로컬 집계합니다.</div></div><div className="panel recommend-panel"><div className="panel-head"><div><h2>데이터 보관</h2><p>현재 저장 상태</p></div><span className="spark">⌂</span></div><div className="recommend-card"><div className="rec-top"><span className="rec-icon">◷</span><span>로컬 전용 저장</span></div><h3>{data.apps.length ? `${data.apps.length}개 앱 활동을 기록 중입니다` : '아직 기록된 데이터가 없습니다'}</h3><p>activity.json 파일은 Windows 앱 데이터 폴더에만 저장되며 네트워크로 전송되지 않습니다.</p><button onClick={()=>setSettings(true)}>저장 및 삭제 설정 <span>→</span></button></div></div></section><section className="panel timeline-panel"><div className="panel-head"><div><h2>타임라인</h2><p>실제 앱 전환과 분당 활동 스냅샷</p></div><span className="period">{data.minute_snapshots.length}분 기록</span></div><div className="timeline-list">{data.timeline.slice(-12).reverse().map((e,i)=><div className="timeline-item" key={`${e.at}-${i}`}><span className="timeline-dot"/><div><b>{time(e.at)} · {e.app || '알 수 없는 창'}</b><small>{e.title || '활성 창 전환'}</small></div></div>)}{!data.timeline.length && <div className="empty-state">앱을 전환하면 실제 타임라인이 기록됩니다.</div>}</div></section></div></main>
 {settings && <div className="modal-backdrop"><div className="settings-modal"><div className="modal-title"><div><h2>설정 · 개인정보</h2><p>FlowLens가 저장하는 데이터와 권한을 관리합니다.</p></div><button className="close" onClick={()=>setSettings(false)}>×</button></div><div className="setting-row"><div><b>활동 추적</b><small>활성 창, 앱 사용 시간, 키보드/마우스 이벤트 수만 집계합니다.</small></div><button className="track-btn" onClick={toggle}>{data.enabled?'일시정지':'시작'}</button></div><div className="setting-row danger"><div><b>수집된 데이터 전체 삭제</b><small>앱별 시간, 전환 횟수, 포커스 시간, 입력량을 로컬 파일에서 영구 삭제합니다.</small></div><button className="delete-btn" onClick={()=>setConfirm(true)}>전체 삭제</button></div><div className="modal-foot">외부 전송: 없음 · 저장 위치: Windows 앱 데이터 폴더 · 화면/키 입력 내용: 저장하지 않음</div></div></div>}
 {confirm && <div className="modal-backdrop"><div className="confirm-modal"><h2>모든 데이터를 삭제할까요?</h2><p>이 작업은 되돌릴 수 없습니다. 저장된 활동 집계와 앱 목록이 즉시 삭제됩니다.</p><div><button className="cancel-btn" onClick={()=>setConfirm(false)}>취소</button><button className="delete-btn" onClick={clear}>삭제</button></div></div></div>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
