import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { invoke } from '@tauri-apps/api/core';
import './styles.css';

type AppActivity = { app: string; title: string; seconds: number; active_millis?: number; activations: number };
type TimelineEvent = { at: string; app: string; title: string; kind: string };
type WorkSession = { started_at: string; ended_at?: string; active_seconds: number; idle_seconds: number; switch_count: number; app_count: number };
type Advanced = { notification_requested: boolean; notification_access: string; per_app_network_requested: boolean; per_app_network_status: string; helper_last_error: string };
type Feature = { date: string; focus_minutes: number; idle_minutes: number; active_ratio: number; app_count: number; context_switches: number; switches_per_active_hour: number; average_session_minutes: number; session_count: number; keyboard_events_per_active_minute: number; mouse_distance_per_active_minute: number; mouse_clicks_per_active_minute: number; click_interval_variance_ms: number; network_bytes_per_active_minute: number; peak_focus_hour: number; work_start_hour?: number; work_end_hour?: number; work_span_hours: number; app_time_share: number[]; local_only: boolean };
type Insight = { level: string; title: string; detail: string };
type SimilarDay = { date: string; similarity: number; focus_delta_minutes: number; switch_delta: number; active_ratio_delta: number };
type EmbeddingRecord = { date: string; dimensions: number; data_confidence: number; embedding: number[]; feature: Feature };
type EmbeddingAnalysis = { enabled: boolean; local_only: boolean; dimensions: number; history_days: number; current?: EmbeddingRecord; baseline_similarity?: number; similar_days: SimilarDay[]; insights: Insight[]; notice: string };
type DashboardData = { enabled: boolean; active_window: string; keyboard_actions: number; mouse_actions: number; app_activation_count: number; focus_seconds: number; hourly_focus: number[]; apps: AppActivity[]; timeline: TimelineEvent[]; minute_snapshots: unknown[]; active_app_count: number; mouse_distance_px: number; mouse_clicks: number; avg_click_interval_ms: number; network_rx_bytes: number; network_tx_bytes: number; notification_count: number; idle_seconds: number; context_switches: number; sessions: WorkSession[]; last_input_age_seconds: number; resume_latency_seconds: number; tracker_sample_interval_ms?: number; unresolved_window_count?: number; daily_feature: Feature; embedding_enabled: boolean; embedding_history: EmbeddingRecord[]; advanced: Advanced };

const blankFeature: Feature = { date:'', focus_minutes:0, idle_minutes:0, active_ratio:0, app_count:0, context_switches:0, switches_per_active_hour:0, average_session_minutes:0, session_count:0, keyboard_events_per_active_minute:0, mouse_distance_per_active_minute:0, mouse_clicks_per_active_minute:0, click_interval_variance_ms:0, network_bytes_per_active_minute:0, peak_focus_hour:0, work_span_hours:0, app_time_share:[], local_only:true };
const blankAnalysis: EmbeddingAnalysis = { enabled:false, local_only:true, dimensions:24, history_days:0, similar_days:[], insights:[], notice:'임베딩 분석을 활성화하면 이 기기에서만 업무 패턴을 비교합니다.' };
const empty: DashboardData = { enabled:true, active_window:'', keyboard_actions:0, mouse_actions:0, app_activation_count:0, focus_seconds:0, hourly_focus:Array(24).fill(0), apps:[], timeline:[], minute_snapshots:[], active_app_count:0, mouse_distance_px:0, mouse_clicks:0, avg_click_interval_ms:0, network_rx_bytes:0, network_tx_bytes:0, notification_count:0, idle_seconds:0, context_switches:0, sessions:[], last_input_age_seconds:0, resume_latency_seconds:0, tracker_sample_interval_ms:200, unresolved_window_count:0, daily_feature:blankFeature, embedding_enabled:false, embedding_history:[], advanced:{ notification_requested:false, notification_access:'not_requested', per_app_network_requested:false, per_app_network_status:'not_requested', helper_last_error:'' } };
const colors = ['#a78bfa','#49d3a0','#f6ad6a','#6cc9f0','#ec86b3','#8bb8ff'];
const minuteText = (seconds:number) => seconds < 60 ? `${seconds}초` : `${Math.floor(seconds / 60)}분`;
const hourText = (seconds:number) => `${Math.floor(seconds / 3600)}h ${Math.floor((seconds % 3600) / 60)}m`;
const bytes = (value:number) => value < 1024 ? `${value} B` : value < 1024 ** 2 ? `${(value / 1024).toFixed(1)} KB` : value < 1024 ** 3 ? `${(value / 1024 ** 2).toFixed(1)} MB` : `${(value / 1024 ** 3).toFixed(2)} GB`;
const activityDuration = (app: AppActivity) => { const milliseconds = app.active_millis ?? app.seconds * 1000; return milliseconds < 1000 ? `${milliseconds}ms` : minuteText(Math.floor(milliseconds / 1000)); };
const stamp = (value:string) => new Date(value).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});
const signed = (value:number, suffix:string) => `${value >= 0 ? '+' : ''}${value.toFixed(value === 0 ? 0 : 1)}${suffix}`;
function Icon({ name }: { name: string }) { const map:Record<string,string> = { grid:'M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z', trend:'M4 17l5-5 3 3 7-8M15 7h4v4', clock:'M12 7v5l3 2M21 12a9 9 0 11-18 0 9 9 0 0118 0', mouse:'M12 2a7 7 0 017 7v6a7 7 0 01-14 0V9a7 7 0 017-7zm0 0v6', shield:'M12 3l7 3v5c0 4.8-3 8.4-7 10-4 1.6-7 5.2-7 10V6l7-3z', settings:'M12 15.5a3.5 3.5 0 100-7 3.5 3.5 0 000 7zM19.4 15a1.8 1.8 0 000 2.5l.1.1-1.8 1.8-.1-.1a1.8 1.8 0 00-2.5 0 1.8 1.8 0 00-.5 1.2v.2h-2.6v-.2a1.8 1.8 0 00-3.1-1.2 1.8 1.8 0 00-2.5 0l-.1.1-1.8-1.8.1-.1a1.8 1.8 0 000-2.5 1.8 1.8 0 00-1.2-.5h-.2v-2.6h.2a1.8 1.8 0 001.2-3.1 1.8 1.8 0 000-2.5l-.1-.1 1.8-1.8.1.1a1.8 1.8 0 002.5 0 1.8 1.8 0 00.5-1.2v-.2h2.6v.2a1.8 1.8 0 003.1 1.2 1.8 1.8 0 002.5 0l.1-.1 1.8 1.8-.1.1a1.8 1.8 0 000 2.5 1.8 1.8 0 001.2.5h.2v2.6h-.2a1.8 1.8 0 00-1.2.5z' }; return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={map[name] || map.grid}/></svg>; }

function App() {
 const [data,setData] = useState<DashboardData>(empty); const [analysis,setAnalysis] = useState<EmbeddingAnalysis>(blankAnalysis); const [tab,setTab] = useState('overview'); const [settings,setSettings] = useState(false); const [confirm,setConfirm] = useState(false); const [advancedOpen,setAdvancedOpen] = useState(false); const [embeddingConfirm,setEmbeddingConfirm] = useState(false); const [now,setNow] = useState(new Date());
 const refresh = async () => { try { const [state,embedding] = await Promise.all([invoke<DashboardData>('get_tracking_state'),invoke<EmbeddingAnalysis>('get_embedding_analysis')]); setData(state); setAnalysis(embedding); } catch { /* browser preview deliberately contains no generated activity data */ } };
 useEffect(() => { refresh(); const timer = setInterval(() => { refresh(); setNow(new Date()); }, 2000); return () => clearInterval(timer); }, []);
 useEffect(() => { const target = tab === 'timeline' ? '.timeline-panel' : tab === 'embedding' ? '.embedding-panel' : tab === 'features' ? '.feature-panel' : ''; if (target) document.querySelector(target)?.scrollIntoView({ behavior:'smooth', block:'start' }); }, [tab]);
 const toggle = async () => { try { setData(await invoke<DashboardData>('set_tracking',{enabled:!data.enabled})); } catch {} };
 const clear = async () => { try { await invoke('clear_all_data'); setData({ ...empty, enabled:data.enabled }); setAnalysis(blankAnalysis); setConfirm(false); } catch {} };
 const enableEmbedding = async () => { try { const next = await invoke<EmbeddingAnalysis>('set_embedding_enabled',{enabled:true}); setAnalysis(next); setData(old => ({...old,embedding_enabled:true})); setEmbeddingConfirm(false); } catch {} };
 const disableEmbedding = async () => { try { const next = await invoke<EmbeddingAnalysis>('set_embedding_enabled',{enabled:false}); setAnalysis(next); setData(old => ({...old,embedding_enabled:false})); } catch {} };
 const clearEmbedding = async () => { try { await invoke('clear_embedding_data'); setData(old => ({...old,embedding_enabled:false,embedding_history:[]})); setAnalysis(blankAnalysis); } catch {} };
 const requestNetwork = async () => { try { const advanced = await invoke<Advanced>('request_per_app_network_collection'); setData(old => ({...old,advanced})); } catch {} };
 const requestNotifications = async () => { try { const advanced = await invoke<Advanced>('request_notification_access'); setData(old => ({...old,advanced})); } catch {} };
 const apps = useMemo(() => [...data.apps].sort((a,b) => b.seconds-a.seconds).slice(0,6),[data.apps]); const maxHour = Math.max(1,...data.hourly_focus); const feature = data.daily_feature || blankFeature; const idle = data.last_input_age_seconds >= 300;
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">F</div><span>FlowLens</span><span className="beta">LOCAL</span></div><div className="workspace"><div className="workspace-avatar">JB</div><div><strong>JB's workspace</strong><small>이 기기에서만 분석</small></div></div><nav>{[['overview','grid','개요'],['focus','trend','집중 분석'],['timeline','clock','타임라인'],['embedding','shield','패턴 분석'],['devices','mouse','활동 추적']].map(([id,icon,label]) => <button key={id} className={tab===id?'nav-item active':'nav-item'} onClick={() => setTab(id)}><Icon name={icon}/><span>{label}</span></button>)}</nav><div className="side-bottom"><button className="nav-item" onClick={() => setSettings(true)}><Icon name="settings"/><span>설정</span></button><div className="privacy-note"><span className="lock">⌑</span><div><b>외부 전송 없음</b><small>이벤트·임베딩·분석 결과는 이 기기에만 저장됩니다.</small></div></div><div className="version">FlowLens v0.5.4</div></div></aside>
  <main className="main"><header className="topbar"><div><p className="eyebrow">LOCAL WORK PATTERN ANALYTICS</p><h1>오늘의 업무 흐름, JB <span>✦</span></h1></div><div className="header-actions"><div className="live"><i className={data.enabled?'pulse':''}/>{data.enabled?(idle?'유휴 감지':'실제 추적 중'):'추적 일시정지'} <span>·</span>{now.toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</div><button className="avatar">JB</button></div></header><div className="content">
   <div className="toolbar"><div className="tabs"><button className="selected">오늘</button><button disabled>이번 주</button><button disabled>이번 달</button></div><button className="track-btn" onClick={toggle}><i className={data.enabled?'pulse':''}/>{data.enabled?'추적 일시정지':'추적 시작'}</button></div>
   <section className="metrics"><Metric icon="clock" accent="purple" label="실제 집중 시간" value={hourText(data.focus_seconds)} detail={`${data.apps.length}개 앱 · 유휴 ${minuteText(data.idle_seconds)}`}/><Metric icon="trend" accent="orange" label="컨텍스트 전환" value={`${data.context_switches}회`} detail={`활성 1시간당 ${feature.switches_per_active_hour.toFixed(1)}회`}/><Metric icon="mouse" accent="blue" label="입력 리듬" value={`${(data.keyboard_actions+data.mouse_actions).toLocaleString()}`} detail={`클릭 ${data.mouse_clicks}회 · 평균 ${data.avg_click_interval_ms}ms`}/></section>
   <section className="metrics"><Metric icon="mouse" accent="blue" label="마우스 이동 거리" value={`${Math.round(data.mouse_distance_px).toLocaleString()} px`} detail={`집중 1분당 ${feature.mouse_distance_per_active_minute.toFixed(0)}px`}/><Metric icon="trend" accent="orange" label="네트워크 총량" value={bytes(data.network_rx_bytes+data.network_tx_bytes)} detail={`수신 ${bytes(data.network_rx_bytes)} · 송신 ${bytes(data.network_tx_bytes)}`}/><Metric icon="shield" accent="purple" label="로컬 임베딩" value={analysis.enabled?`${analysis.dimensions}차원`:'꺼짐'} detail={analysis.enabled?`${analysis.history_days}일 이력 · 외부 전송 없음`:'명시적으로 켜야 분석함'}/></section>
   <section className="grid-top"><div className="panel focus-panel"><div className="panel-head"><div><h2>집중 · 유휴 흐름</h2><p>입력 이벤트 기반 로컬 활동 강도</p></div><div className="legend"><i/>활성 창 포커스</div></div><div className="hour-bars">{data.hourly_focus.map((value,index) => <div className="hour-bar" key={index}><i style={{height:`${Math.max(3,value/maxHour*100)}%`}}/><small>{index%3===0?`${String(index).padStart(2,'0')}:00`:''}</small></div>)}</div><div className="insight"><span className="insight-icon">✦</span><div><b>{feature.focus_minutes?`${String(feature.peak_focus_hour).padStart(2,'0')}:00가 오늘의 피크 집중 시간입니다`:'작업을 시작하면 실제 특징점이 계산됩니다'}</b><p>{feature.focus_minutes?`활성 비율 ${(feature.active_ratio*100).toFixed(0)}% · 평균 세션 ${feature.average_session_minutes.toFixed(1)}분 · 입력 후 유휴 임계값 5분`:'화면·텍스트를 저장하지 않고 시간·전환·입력량·거리만 집계합니다.'}</p></div></div></div>
   <div className="panel apps-panel"><div className="panel-head"><div><h2>실제 사용 앱</h2><p>창 핸들·PID·실행 파일명 기준 로컬 집계</p></div><span className="period">{data.tracker_sample_interval_ms || 200}ms</span></div>{apps.length?<div className="app-list">{apps.map((app,index)=>{ const leading = apps[0].active_millis ?? apps[0].seconds * 1000; const current = app.active_millis ?? app.seconds * 1000; return <div className="app-row" key={app.app}><div className="app-symbol" style={{background:colors[index%colors.length]}}>{app.app.slice(0,1).toUpperCase()}</div><div className="app-info"><div><b title={app.app}>{app.app}</b><span>{activityDuration(app)}</span></div><small>{app.title}</small><div className="progress"><i style={{width:`${Math.max(4,current / Math.max(1,leading) * 100)}%`,background:colors[index%colors.length]}}/></div></div><span className="rank">{String(index+1).padStart(2,'0')}</span></div>})}</div>:<div className="empty-state">활성 앱 데이터 수집 대기 중</div>}<div className="tracker-status">{data.unresolved_window_count ? `보호된 창 또는 접근 제한 창 ${data.unresolved_window_count}회는 PID 기반 대체 식별자로 기록되었습니다.` : '무제목 창과 제목이 변경되는 창도 실행 파일명 기준으로 같은 앱에 누적합니다.'}</div></div></section>
   <section className="panel embedding-panel"><div className="panel-head"><div><h2>업무 패턴 임베딩</h2><p>24차원 수치형 벡터 · 코사인 유사도 · 온디바이스 분석</p></div><div className="embedding-actions">{analysis.enabled?<><span className="period on">LOCAL ON</span><button className="mini-btn" onClick={disableEmbedding}>분석 끄기</button></>:<button className="track-btn" onClick={() => setEmbeddingConfirm(true)}>로컬 분석 활성화</button>}</div></div>{analysis.enabled?<><div className="embedding-summary"><div><span>개인 기준선 유사도</span><strong>{analysis.baseline_similarity===undefined?'학습 중':`${Math.round(analysis.baseline_similarity*100)}%`}</strong><small>이전 업무일 평균과의 벡터 유사도</small></div><div><span>오늘 데이터 신뢰도</span><strong>{analysis.current?`${Math.round(analysis.current.data_confidence*100)}%`:'0%'}</strong><small>집중 시간 기반의 표본 충분성</small></div><div><span>저장된 업무일</span><strong>{analysis.history_days}일</strong><small>최대 365일 · 설정에서 삭제 가능</small></div></div><div className="embedding-columns"><div><h3>설명 가능한 패턴</h3><div className="insight-list">{analysis.insights.map((item,index)=><div className={`pattern-insight ${item.level}`} key={index}><i>{item.level==='positive'?'↗':item.level==='attention'?'!':'•'}</i><div><b>{item.title}</b><p>{item.detail}</p></div></div>)}</div></div><div><h3>가장 유사한 업무일</h3>{analysis.similar_days.length?<div className="similar-list">{analysis.similar_days.map(day=><div className="similar-day" key={day.date}><div><b>{day.date}</b><small>집중 {signed(day.focus_delta_minutes,'분')} · 전환 {signed(day.switch_delta,'회/h')}</small></div><strong>{Math.round(day.similarity*100)}%</strong></div>)}</div>:<div className="embedding-empty">하루 이상 축적되면 유사한 업무일을 비교합니다.</div>}</div></div><div className="embedding-notice">{analysis.notice}</div></>:<div className="embedding-off"><div className="embedding-orbit"><i/><i/><i/></div><div><h3>내 업무 리듬을 로컬 벡터로 비교하세요</h3><p>집중·유휴·세션·전환·입력 리듬·시간대·앱 시간 비율을 <b>24차원 수치형 벡터</b>로 정규화합니다. 원본 창 제목, 키 입력, URL, 화면 내용은 임베딩에 포함되지 않습니다.</p><button className="track-btn" onClick={() => setEmbeddingConfirm(true)}>로컬 분석 활성화</button></div></div>}</section>
   <section className="grid-bottom"><div className="panel feature-panel"><div className="panel-head"><div><h2>임베딩 입력 특징</h2><p>원본 활동 데이터를 대체하는 로컬 수치형 특징</p></div><span className="period">24D · local</span></div><div className="feature-grid"><Feature name="세션 평균" value={`${feature.average_session_minutes.toFixed(1)}분`}/><Feature name="유휴 시간" value={`${feature.idle_minutes.toFixed(1)}분`}/><Feature name="키보드 밀도" value={`${feature.keyboard_events_per_active_minute.toFixed(1)}/분`}/><Feature name="클릭 리듬" value={`${feature.mouse_clicks_per_active_minute.toFixed(1)}/분`}/><Feature name="활성 앱 다양성" value={`${feature.app_count}개`}/><Feature name="네트워크 밀도" value={`${bytes(Math.round(feature.network_bytes_per_active_minute))}/분`}/></div><div className="vector-note">특징은 정규화된 수치로만 임베딩됩니다. 앱 이름·창 제목·입력값은 분석기와 유사도 계산에 전달되지 않습니다.</div></div>
   <div className="panel recommend-panel"><div className="panel-head"><div><h2>고급 수집</h2><p>권한이 필요한 선택 기능</p></div><span className="spark">⌂</span></div><div className="recommend-card"><div className="rec-top"><span className="rec-icon">⌑</span><span>명시적 승인 필요</span></div><h3>알림·앱별 네트워크는 기본 수집에서 제외됩니다</h3><p>알림은 Windows 동의와 MSIX 패키지가, 앱별 네트워크는 관리자 권한 ETW 수집기가 필요합니다.</p><button onClick={() => setAdvancedOpen(true)}>권한 및 상태 확인 <span>→</span></button></div></div></section>
   <section className="panel timeline-panel"><div className="panel-head"><div><h2>타임라인</h2><p>앱 전환 및 작업 세션의 실제 이벤트</p></div><span className="period">{data.timeline.length} 이벤트</span></div><div className="timeline-list">{data.timeline.slice(-15).reverse().map((event,index)=><div className="timeline-item" key={`${event.at}-${index}`}><span className="timeline-dot"/><div><b>{stamp(event.at)} · {event.kind==='app_switch'?'앱 전환':event.kind==='session_start'?'세션 시작':'유휴로 세션 종료'}</b><small>{event.app||'알 수 없는 창'}</small></div></div>)}{!data.timeline.length&&<div className="empty-state">앱을 전환하거나 작업을 시작하면 실제 타임라인이 기록됩니다.</div>}</div></section>
  </div></main>
  {settings&&<div className="modal-backdrop"><div className="settings-modal"><div className="modal-title"><div><h2>설정 · 개인정보</h2><p>추적 데이터와 임베딩은 이 기기에서만 관리됩니다.</p></div><button className="close" onClick={() => setSettings(false)}>×</button></div><div className="setting-row"><div><b>기본 행동 추적</b><small>앱 전환, 활동 시간, 유휴 구간, 키보드/마우스 집계, 네트워크 전체량을 로컬에 기록합니다.</small></div><button className="track-btn" onClick={toggle}>{data.enabled?'일시정지':'시작'}</button></div><div className="setting-row"><div><b>로컬 업무 패턴 임베딩</b><small>수치형 특징 24개와 일별 유사도만 저장합니다. 원본 제목·입력·URL은 임베딩하지 않습니다.</small></div><button className="track-btn" onClick={analysis.enabled?disableEmbedding:() => setEmbeddingConfirm(true)}>{analysis.enabled?'분석 끄기':'활성화'}</button></div>{analysis.enabled&&<div className="setting-row danger"><div><b>임베딩 분석 데이터 삭제</b><small>보존된 일별 벡터, 유사 업무일 이력 및 기준선을 삭제합니다. 원천 활동 데이터는 유지됩니다.</small></div><button className="delete-btn" onClick={clearEmbedding}>분석 데이터 삭제</button></div>}<div className="setting-row"><div><b>고급 수집 권한</b><small>알림 수와 앱별 네트워크 사용량은 별도의 OS 권한·선택 수집기가 필요합니다.</small></div><button className="track-btn" onClick={() => setAdvancedOpen(true)}>관리</button></div><div className="setting-row danger"><div><b>수집 데이터 전체 삭제</b><small>원천 이벤트, 타임라인, 세션, 분당 스냅샷, 임베딩을 모두 영구 삭제합니다.</small></div><button className="delete-btn" onClick={() => setConfirm(true)}>전체 삭제</button></div><div className="modal-foot">외부 전송: 없음 · 화면/문서 본문/키 입력 내용/URL: 저장하지 않음</div></div></div>}
  {advancedOpen&&<div className="modal-backdrop"><div className="settings-modal advanced-modal"><div className="modal-title"><div><h2>고급 수집 권한</h2><p>기본 추적과 별도이며, 활성화 전 수집 범위와 권한을 명확히 안내합니다.</p></div><button className="close" onClick={() => setAdvancedOpen(false)}>×</button></div><div className="permission-card"><div><b>Windows 알림 횟수</b><small>관리자 권한이 아니라 <b>MSIX 패키지 identity</b>와 Windows의 <b>알림 접근 동의</b>가 필요합니다. 알림 본문은 수집하지 않고 추가된 알림의 개수와 앱 식별자만 집계하도록 설계됩니다.</small></div><span className={data.advanced.notification_requested?'status pending':'status'}>{data.advanced.notification_requested?'MSIX 필요':'미설정'}</span><button className="track-btn" onClick={requestNotifications}>요구사항 기록</button></div><div className="permission-card"><div><b>앱별 네트워크 사용량</b><small>시스템 ETW 이벤트에서 프로세스별 송·수신 바이트를 집계합니다. 선택 수집기를 시작할 때 Windows UAC 관리자 승인과 수집 범위 확인이 필요합니다. 패킷, URL, IP는 저장하지 않습니다.</small></div><span className={data.advanced.per_app_network_requested?'status pending':'status'}>{data.advanced.per_app_network_requested?'승격 수집기 필요':'미설정'}</span><button className="delete-btn" onClick={requestNetwork}>관리자 필요 안내</button></div>{data.advanced.helper_last_error&&<div className="advanced-note">{data.advanced.helper_last_error}</div>}<div className="modal-foot">현재 MSI/EXE 빌드는 고급 모듈을 자동 실행하지 않습니다. 사용자 동의 없이 관리자 권한을 요청하거나 시스템 수준 이벤트를 수집하지 않습니다.</div></div></div>}
  {embeddingConfirm&&<div className="modal-backdrop"><div className="confirm-modal embedding-confirm"><span className="modal-chip">LOCAL ONLY</span><h2>로컬 업무 패턴 분석을 활성화할까요?</h2><p>집중·유휴·세션·전환·입력 리듬·시간대·앱 시간 비율을 <b>24차원 수치형 벡터</b>로 이 기기에만 저장합니다. 원본 창 제목, 키 입력, URL, 화면 내용은 임베딩에 포함되지 않으며 외부 API로 전송하지 않습니다.</p><div><button className="cancel-btn" onClick={() => setEmbeddingConfirm(false)}>취소</button><button className="track-btn" onClick={enableEmbedding}>로컬 분석 활성화</button></div></div></div>}
  {confirm&&<div className="modal-backdrop"><div className="confirm-modal"><h2>모든 데이터를 삭제할까요?</h2><p>활동 집계, 타임라인, 세션, 특징 벡터, 임베딩 이력과 고급 수집 권한 상태가 함께 삭제됩니다. 이 작업은 되돌릴 수 없습니다.</p><div><button className="cancel-btn" onClick={() => setConfirm(false)}>취소</button><button className="delete-btn" onClick={clear}>삭제</button></div></div></div>}
 </div>;
}
function Metric({icon,accent,label,value,detail}:{icon:string;accent:string;label:string;value:string;detail:string}) { return <div className="metric-card"><div className={`metric-icon ${accent}`}><Icon name={icon}/></div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div>; }
function Feature({name,value}:{name:string;value:string}) { return <div className="feature-item"><span>{name}</span><b>{value}</b></div>; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
